import type { NextPage } from "next";

import { HeadMeta } from "../components";

const LicenseTerms: NextPage = () => (
  <>
    <HeadMeta />
    <div className="relative overflow-hidden text-white">
      <div className="bg-gray-900 bg-gradient-to-br from-[#da10109e] via-transparent to-[#da10109e] pt-10 sm:pt-16 lg:overflow-hidden lg:pt-8 lg:pb-14">
        <div className="mx-auto max-w-7xl lg:px-8">
          <h1 className="pb-6 lg:text-2xl lg:font-bold lg:italic">
            TERMS & CONDITIONS
          </h1>
          <p>
            Optichads is a collection of digital artworks (NFTs) running on the
            Ethereum network. This website is only an interface allowing
            participants to exchange digital collectibles. Users are entirely
            responsible for the safety and management of their own private
            Ethereum wallets and validating all transactions and contracts
            generated by this website before approval. Furthermore, as the
            Optichad smart contract runs on the Ethereum network, there is no
            ability to undo, reverse, or restore any transactions.
          </p>
          <br />
          <p className="pb-6">
            This website and its connected services are provided “as is” and “as
            available” without warranty of any kind. By using this website you
            are accepting sole responsibility for any and all transactions
            involving Optichad digital collectibles.
          </p>
          <h1 className="pb-6 lg:text-2xl lg:font-bold lg:italic">OWNERSHIP</h1>
          <p>
            i. You Own the NFT. Each Optichad is an NFT on the Ethereum
            blockchain. When you purchase an NFT, you own the underlying
            Optichad, the Art, completely. Ownership of the NFT is mediated
            entirely by the Smart Contract and the Ethereum Network: at no point
            may we seize, freeze, or otherwise modify the ownership of any Optichad.
          </p>
          <br />
          <p className="pb-6">
            ii. Personal Use. Subject to your continued compliance with these
            Terms, Rollup Labs LLC grants you a worldwide, royalty-free license to
            use, copy, and display the purchased Art, along with any extensions
            that you choose to create or use, solely forthe following purposes:
            (i) for your own personal, non-commercial use; (ii) as part of a
            marketplace that permits the purchase and sale of your Optichad /
            NFT, provided that the marketplace cryptographically verifies each
            Optichad owner’s rights to display the Art for their Optichad to
            ensure that only the actual owner can display the Art; or (iii) as
            part of a third party website or application that permits the
            inclusion, involvement, or participation of your Optichad, provided
            that the website/application cryptographically verifies each Optichad
            owner’s rights to display the Art for their Optichad to ensure
            that only the actual owner can display the Art, and provided that
            the Art is no longer visible once the owner of the Optichad leaves
            the website/application.
          </p>
          <br />
          <p>
            iii. Commercial Use. Subject to your continued compliance with these
            Terms, Rollup Labs LLC grants you an unlimited, worldwide license to
            use, copy, and display the purchased Art for the purpose of creating
            derivative works based upon the Art (“Commercial Use”). Examples of
            such Commercial Use would e.g. be the use of the Art to produce and
            sell merchandise products (T-Shirts etc.) displaying copies of the
            Art. For the sake of clarity, nothing in this Section will be deemed
            to restrict you from (i) owning or operating a marketplace that
            permits the use and sale of Optichads generally, provided that the
            marketplace cryptographically verifies each Optichad owner’s rights
            to display the Art for their Optichad to ensure that only the
            actual owner can display the Art; (ii) owning or operating a third
            party website or application that permits the inclusion,
            involvement, or participation of Optichads generally, provided that
            the third party website or application cryptographically verifies
            each Optichad owner’s rights to display the Art for their Optichad
            to ensure that only the actual owner can display the Art, and
            provided that the Art is no longer visible once the owner of the
            Purchased Optichad leaves the website/application; or (iii) earning
            revenue from any of the foregoing.
          </p>
        </div>
      </div>
    </div>
  </>
);

export default LicenseTerms;
